# Generated by Django 3.0.5 on 2020-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_us_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='res_atend_realizado',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Atendimento Realizado'),
        ),
    ]
