# Generated by Django 3.0.5 on 2020-05-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200506_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='res_nome_cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='res_telefone',
        ),
    ]
