# Generated by Django 3.0.5 on 2020-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200506_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='res_nome_cliente',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='reserva',
            name='res_telefone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
