# Generated by Django 3.0.5 on 2020-05-14 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200506_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='res_avaliacao',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='res_obs_avaliacao',
        ),
        migrations.AddField(
            model_name='reserva',
            name='res_periodo',
            field=models.CharField(choices=[('9-10', 'Das 9hr as 10hrs'), ('10-11', 'Das 10hr as 11hrs'), ('13-14', 'Das 13hr as 14hrs'), ('14-15', 'Das 14hr as 15hrs'), ('15-16', 'Das 15hr as 16hrs'), ('16-17', 'Das 16hr as 17hrs'), ('17-18', 'Das 17hr as 18hrs'), ('18-19', 'Das 18hr as 19hrs'), ('19-20', 'Das 19hr as 20hrs')], default=datetime.datetime(2020, 5, 14, 21, 33, 44, 803758, tzinfo=utc), max_length=18, verbose_name='Período'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_data_reserva',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_nome_cliente',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_obs_atend',
            field=models.TextField(blank=True, verbose_name='Observações sobre o atendimento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
    ]
