# Generated by Django 3.0.5 on 2020-05-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200515_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='serv_alter_usuario_id',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='serv_data_alter',
        ),
    ]
