# Generated by Django 3.0.5 on 2020-05-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200515_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='serv_tempo_duracao',
        ),
    ]
