# Generated by Django 3.0.5 on 2020-05-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200516_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
