# Generated by Django 3.0.5 on 2020-05-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_data_realizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Realização')),
                ('res_nome_cliente', models.CharField(max_length=60, verbose_name='Nome Cliente')),
                ('res_telefone_cliente', models.CharField(max_length=11, verbose_name='Telefone Cliente')),
                ('res_data_atendimento', models.DateField(verbose_name='Data Atendimento')),
                ('res_periodo_atendimento', models.CharField(choices=[('9-10', 'Das 9hr as 10hrs'), ('10-11', 'Das 10hr as 11hrs'), ('13-14', 'Das 13hr as 14hrs'), ('14-15', 'Das 14hr as 15hrs'), ('15-16', 'Das 15hr as 16hrs'), ('16-17', 'Das 16hr as 17hrs'), ('17-18', 'Das 17hr as 18hrs'), ('18-19', 'Das 18hr as 19hrs'), ('19-20', 'Das 19hr as 20hrs')], max_length=5, verbose_name='Periodo Atendimento')),
                ('res_especialista', models.CharField(choices=[('Chiquinho Oliveira', 'Chiquinho Oliveira'), ('Sandrinho Santos', 'Sandrinho Santos')], max_length=60, verbose_name='Especialista')),
            ],
        ),
    ]
