# Generated by Django 3.0.5 on 2020-05-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='res_especialista',
            field=models.CharField(max_length=60, verbose_name='Especialista'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_periodo_atendimento',
            field=models.CharField(max_length=5, verbose_name='Periodo Atendimento'),
        ),
    ]
