# Generated by Django 3.0.5 on 2020-05-18 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200516_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='res_servicos',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Servicos'),
            preserve_default=False,
        ),
    ]
