# Generated by Django 3.0.5 on 2020-05-19 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_reserva_res_email_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='res_email_cliente',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
