# Generated by Django 3.0.5 on 2020-05-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_usuario_res_email_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='res_email_cliente',
            new_name='res_email',
        ),
    ]
