# Generated by Django 3.0.5 on 2020-05-21 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200519_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='res_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=9, verbose_name='Situação'),
            preserve_default=False,
        ),
    ]
