# Generated by Django 3.0.5 on 2020-05-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_reserva_res_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='res_data_realizacao',
        ),
        migrations.AddField(
            model_name='reserva',
            name='res_agendado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Agendado Em'),
        ),
    ]
