# Generated by Django 3.0.5 on 2020-05-25 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200525_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='res_observacao',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Observações'),
            preserve_default=False,
        ),
    ]
