# Generated by Django 3.0.5 on 2020-05-26 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reserva_res_codigo_verificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='res_observacao_especialista',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Observações'),
            preserve_default=False,
        ),
    ]
