# Generated by Django 3.0.5 on 2020-05-26 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_reserva_res_observacao_especialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='res_avaliacao',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='Avaliar Atendimento'),
            preserve_default=False,
        ),
    ]
