# Generated by Django 3.0.5 on 2020-05-26 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_reserva_res_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='res_observacao_avaliacao',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, verbose_name='Código de Verificação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='res_codigo_verificacao',
            field=models.CharField(max_length=10, verbose_name='Código de Verificação'),
        ),
    ]
