# Generated by Django 3.0.5 on 2020-05-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200526_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='res_avaliacao',
            field=models.CharField(max_length=10, verbose_name='Avaliar Atendimento'),
        ),
    ]
