# Generated by Django 3.0.5 on 2020-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200527_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='res_avaliacao',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Avaliar Atendimento'),
        ),
    ]
