# Generated by Django 3.0.5 on 2020-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200527_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='res_observacao_avaliacao',
            field=models.TextField(default='', verbose_name='Observação de Verificação'),
        ),
    ]
