# Generated by Django 3.0.5 on 2020-05-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200527_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='estab_alter_usuario_id',
        ),
    ]
