# Generated by Django 3.0.5 on 2020-06-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_estabelecimento_estab_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='serv_status',
            field=models.CharField(default='Ativo', max_length=9, verbose_name='Situação'),
        ),
    ]
