# Generated by Django 3.0.5 on 2020-06-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_servico_serv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='serv_status',
            field=models.CharField(default='Habilitado', max_length=9, verbose_name='Situação'),
        ),
    ]
