# Generated by Django 2.2.12 on 2020-04-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='us_perfil',
            field=models.CharField(choices=[('C', 'Cliente'), ('E', 'Especialista'), ('A', 'Administrador')], default='C', max_length=1, null=True, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_situacao_conta',
            field=models.BooleanField(default=1, null=True, verbose_name='Status da conta'),
        ),
    ]
