# Generated by Django 2.2.12 on 2020-04-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200426_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='us_end_bairro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='us_end_cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='us_end_cidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='us_end_complemento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='us_end_logradouro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='us_end_numero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='us_end_uf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='us_sexo',
        ),
    ]
