# Generated by Django 2.2.12 on 2020-04-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200426_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='us_situacao_conta',
            field=models.BooleanField(default=True, null=True, verbose_name='Conta ativa'),
        ),
    ]
